### ISSUE TITLE
Data Transfer ID is incorrect???

### ISSUE THREAD

**Issue by ColinIsAGoner** [RunnersRevival/revival_issues#100] opened 2024-07-30 21:37 UTC
I've come back to sonic runners revival after like a month or 2 of inactivity, and when im trying to transfer my data, the game tells me i have typed in the wrong transfer ID or password, i triple checked it many times and its not wrong, any solution??

P.S: Im sorry if my english sounds weak, its not my native

**Comment by JKouga** [comment] 2024-07-30 21:56
Your transfer ID and your 10-digit ID are not the same thing (which is intended).  If you're still having issues after that, there could be two potential issues that could be happening:

1. You set your password before in-game transfers worked (in-game transfers did not work until Feb. 12, 2023).
2. You already used said transfer ID once.

For either case, you will need to reset your password again.

**Comment by JKouga** [comment] 2024-07-30 22:00
For future reference, we had many who asked about transferring their data in the past.  Our dev team has yet to find any issue with the in-game transfer system and we have also provided resources on how to do the transfers.

**Comment by ColinIsAGoner** [comment] 2024-07-30 22:56
> Your transfer ID and your 10-digit ID are not the same thing (which is intended). If you're still having issues after that, there could be two potential issues that could be happening:
> 
> 1. You set your password before in-game transfers worked (in-game transfers did not work until Feb. 12, 2023).
> 2. You already used said transfer ID once.
> 
> For either case, you will need to reset your password again.

Reply: Yes i used it once before, is it only usable once?

**Comment by JKouga** [comment] 2024-07-30 23:03
Correct.  Each transfer ID can only be used one time per transfer.  This is the intended behavior.  If you want to use the in-game transfer again, you **must** get a new transfer ID after every use of the in-game transfer.

**Comment by JKouga** [comment] 2024-07-30 23:17
@FairPlay137 @Ramen2X When you guys have the time, please close this issue as this issue is considered invalid/not an issue.

**Closed as not planned** 2024-08-08 02:12 UTC
Labels: Invalid / Not an issue
