### ISSUE TITLE
Negative Rings

### ISSUE THREAD

**Issue by qwertyuiop265000** [RunnersRevival/revival_issues#55] opened 2023-03-07 08:45 UTC
**Description**
1. Negative rings can be obtained. 
2. It prevents you from playing at all.

**To Reproduce**
1. Somehow get negative rings (e.g. upgrading at the speed of sound)
2. Experience hell

**Expected behavior**
My rings should be 0, not negative. 

**Screenshots or videos**
![Screenshot_20230307_032047_Sonic Runners Revival](https://user-images.githubusercontent.com/108723826/223369691-62978416-5419-4414-a7b4-8d93f9afd56e.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Tab S6 Lite
 - OS: Android 13
 - Version: 2.2.3t

**Comment by F121Live** [comment] 2023-03-07 08:50
Duplicate of #46 .

Please read older issues before reporting something.

**Closed** 2023-03-07 08:50 UTC
Labels: Duplicate, Invalid
