### ISSUE TITLE
If you run into a wall as Tails while being invincible, you'll end up getting stuck indefinitely

### ISSUE THREAD

**Issue by 0rangeToast** [RunnersRevival/revival_issues#61] opened 2023-06-27 18:16 UTC
**Describe the bug**

**To Reproduce**
1. Go to any wall while being invincible as tails

**Expected behavior**
that i could get off the wall??

**Screenshots or videos**
yt link: https://youtu.be/QFAx90NMs1Q

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS:  iOS 16.5
 - Version: 2.2.0

**Comment by JKouga** [comment] 2023-06-27 19:39
This is a known issue from the original game.  Your only option is to either use your color power equippable item or your sub character if you have them equipped.  If you do not have any of them, you have to exit the run.

**Comment by FairPlay137** [comment] 2023-06-28 00:44
Duplicate of #20 and #59.

**Closed by FairPlay137** 2023-06-28 00:44 UTC
Labels: Duplicate, Won't Fix
