### ISSUE TITLE
Special Roulette skipped after a run and more than 10 Eggs

### ISSUE THREAD

**Issue by aro24** [RunnersRevival/revival_issues#19] opened 2022-07-06 00:26 UTC
**Describe the bug**
Special Roulette is skipped after a non-dupe Premium Roulette pull and 10+ eggs

**To Reproduce**
1. Have at least 7 Special Eggs
2. Spin the Item Roulette until you pull Buddy duplicate eggs (Results in 10-12 Special Eggs)
3. Complete a run (Story, Event, Timed, does not matter)
4. Pull on the Premium Roulette and DO NOT obtain duplicate Special Eggs

**Expected behavior**
Buddy/Character levels up, Special Roulette is triggered.

**Observed behavior**
Buddy/Character levels up, Special Roulette is skipped, with 0-2 Special Eggs remaining.

**Screenshots or videos**
[Will add if ran into again]

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S8+
 - OS: Android 11
 - Version: 2.2.0t

**Additional context**

**Comment by FairPlay137** [comment] 2022-07-06 22:04
Possibly related to the sloppy implementation of special egg obtainment on the Item Roulette?

**Comment by JKouga** [comment] 2022-07-06 23:41
Do you have Level 10 Normal Buddies by any chance?

**Comment by aro24** [comment] 2022-07-10 00:55
> Do you have Level 10 Normal Buddies by any chance?

Yeah, I believe all my Normal Buddies are level 10.

**Comment by JKouga** [comment] 2022-09-27 16:40
> Possibly related to the sloppy implementation of special egg obtainment on the Item Roulette?

This is from literallydrew:

https://user-images.githubusercontent.com/71540050/192584721-77dc7f72-db4f-4fa9-9c57-90a25a521a77.mov

So it looks like the Special Eggs he got from the Item Roulette after you get a max leveled dupe do not appear until after you spin the Premium Roulette...so, here is the problem.  He had five special eggs prior to this.  Then, he went to the Item Roulette and got more six more special eggs from the Item Roulette based on getting max-leveled dupes from the Item Roulette.  Outrun basically indirectly added those six special eggs (it went from five to one and the Special Roulette does not appear).  When those six eggs were added to the five, he should've gotten the free spin on the Special Roulette.  However, that did not happen, and instead, those six special eggs were added after spinning the Premium Roulette.  At least the Special Eggs you got from the Item Roulette from a max leveled dupe definitely does work, but not the way it was intended.

**Comment by JKouga** [comment] 2022-09-27 16:44
This possibility definitely did happen to aro24, except as he mentioned, he had seven, and those three special eggs he got from the Item Roulette were indirectly added (so basically he went from 7 -> 0.  Then, it's definitely possible that when he spun the Premium Roulette, he got those three special eggs afterwards.

**Comment by JKouga** [comment] 2022-09-28 00:04
Just saw the bug in action today and can confirm that that is what is happening.

**Comment by FairPlay137** [comment] 2023-09-21 06:26
Pushed an experimental fix for this issue; if anyone runs into any issues please follow up.

**Comment by FairPlay137** [comment] 2023-09-21 06:45
Confirmed fixed as of latest server hotfix update.

**Closed by FairPlay137** 2023-09-21 06:45 UTC
Labels: Bug, Server
