### ISSUE TITLE
Tails in a wall.

### ISSUE THREAD

**Issue by GamerestBoi** [RunnersRevival/revival_issues#59] opened 2023-05-23 21:00 UTC
**Describe the bug**
Tails got stuck on a wall in Chasing Our Tails.

**To Reproduce**
1. Go to Chasing Our Tails and jump on a wall and hit a błędnik touching it
2. See error

**Expected behavior**
Tails would just either fall or bounce over the pit.

**Screenshot**
(https://github.com/RunnersRevival/revival_issues/assets/120332996/89caccac-4ea2-4ffa-9339-c1b03bd044e7)

**Smartphone**
 - Device: Oppo A16
 - OS: ColorOS
 - Version: v11

**Additional context**
Before this gets fixed, BEWARE OF ENEMIES TOUCHING WALLS!

**Comment by FairPlay137** [comment] 2023-05-24 04:20
Known physics bug, duplicate of #20.

**Closed by FairPlay137** 2023-05-24 04:20 UTC
Labels: Duplicate, Won't Fix
