### ISSUE TITLE
Streamline Mode mutes all SFX

### ISSUE THREAD

**Issue by BlueStarWB** [RunnersRevival/revival_issues#9] opened 2022-06-27 04:10 UTC
using any of the Streamline functionality also mutes the SFX of the game, no ring noise, no crystal noise and no badnik pop noise.

**To Reproduce**
1. Go to Streamlined mode
2. Click on either tick that activates Streamline mode
3. restart the game and play a stage

**Expected behavior**
Streamline mode to only reduce animation and video quality 

in Sound Settings none of the settings alter but the SFX is gone from the game. could be a carry over bug that Sega never fixed.

**Comment by FairPlay137** [comment] 2022-06-27 05:02
I believe this was an issue that was in the original game as well, as I was able to reproduce it back when Revival used 2.0.3.
It may have been by design, but then again, we cannot be sure.

**Comment by F121Live** [comment] 2022-06-29 02:48
The "Reduce Number of Animations" option is what causes this behaviour, I believe it was intended by the developers as CriWare can take a small % of the CPU usage when decoding the audio.

**Comment by F121Live** [comment] 2022-07-03 06:41
I consider this a deisgn choice, closing as not planned

**Closed by F121Live** 2022-07-03 06:41 UTC
Labels: Client
