### ISSUE TITLE
Exiting the Timed Mode menu back to the Main Menu freezes the game

### ISSUE THREAD

**Issue by sky1300YT** [RunnersRevival/revival_issues#10] opened 2022-06-27 14:10 UTC
**Describe the bug**
Going from Timed Mode Prep menu to Main Menu freezes the game

**To Reproduce**
1. Go to timed mode
2. go back to main menu

**Expected behavior**
I expected the back to main menu button would take me to the main menu from the timed mode prep menu

**Screenshots or videos**
N/A

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy]
 - OS: [Android]
 - Version: [2.2.0]

**Additional context**
I tried to do the event, tried to go to the buddy menu from the timed mode menu, when I hit the back to main menu button, the game froze

**Comment by Ramen2X** [comment] 2022-06-27 15:01
I cannot reproduce this issue, can you provide more information?

**Comment by F121Live** [comment] 2022-08-06 12:48
We couldn't reproduce this issue, closing this.

**Closed by F121Live** 2022-08-06 12:48 UTC
Labels: Client, Unreproducible
